""" 

This module is used for visualizing results generated by the ABM simulation runs. 

The standardized results, stored in the database, are visualized using matplotlib.pyplot, which is wrapped by this module. The module also makes use of pandas.

The module provides a set of pre-defined plotting functions. Data is forwarded to these in the form of input arguments. The functions then create the plots. 
Functionality is also provided for saving plots as pdf or png. Destination directory must be specified in the config-file. Alternatively, paths where plots are saved can be specified as input arguments. 

"""

__author__ = "Linnart Felkl"
__email__ = "linnartsf@gmail.com"


import data
import config
from matplotlib import pyplot as plt
import pandas

plt.style.use("fivethirtyeight")

def warning(msg: str) -> None:
    """ helper function that prints a warning into console; used when invalid input is forwarded to one of the functions in the module """
    print(f"WARING: {msg}")

def set_plotstyle(style: str) -> None:
    """ sets matplotlib plotstyle """
    plt.style.use(style)

def set_fontsizes(smallsize: float, mediumsize: float, largesize: float):
    plt.rc('font', size = smallsize)          # controls default text sizes
    plt.rc('axes', titlesize = smallsize)     # fontsize of the axes title
    plt.rc('axes', labelsize = mediumsize)    # fontsize of the x and y labels
    plt.rc('xtick', labelsize = smallsize)    # fontsize of the tick labels
    plt.rc('ytick', labelsize = smallsize)    # fontsize of the tick labels
    plt.rc('legend', fontsize = smallsize)    # legend fontsize
    plt.rc('figure', titlesize = largesize)   # fontsize of the figure title

def save_plot(filename: str, filepath: str = "") -> None:
    """ stores plot as png and pdf, for specified equipment name """
    if filepath == "": filepath = config.path_saveplots
    plt.savefig(filepath+"\\"+filename+".png")
    plt.savefig(filepath+"\\"+filename+".pdf")

# plot individual agent attribute value trajectory throughout time, for one attribute
# TODO

# plot avg value trajectory for all agents throughout time, for arbitrary amount of attributes
# TODO

# plot, for every time interval, the distribution of agents that have one of the values of respective attribute (stacked bar diagram)
# TODO

# plot grid cell occulation (at least one agent in cell, or none), for "all" agent types or just for one or several agent types (i.e. "populations")
# TODO

# plot grid and intensity of agent population, for "all" agents or one or several agent types
# TODO

# TODO implement additional plot types and plotting options